# These are supported funding model platforms

github: 
patreon: 
open_collective: 
ko_fi: # Replace with a single Ko-fi username
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
custom: https://www.paypal.me/donatemeking
