# These are supported funding model platforms

github: 
patreon: https://www.patreon.com/Kingsiddhu
open_collective: 
ko_fi: # Replace with a single Ko-fi username
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
otechie: 
custom: https://www.paypal.me/siddharthka
