var bookConfig = {
    "FlipSound": "Yes",
    "QRCode": "Show",
    "appLogoIcon": "..\/..\/booklogo.png?1646765895",
    "appLogoLinkURL": "",
    "HomeURL": "",
    "appLogoOpenWindow": "Blank",
    "bookTitle": "FLIPBOOK",
    "bookDescription": "",
    "toolbarColor": "#181818",
    "iconColor": "#e3e3e3",
//    "loadingPicture": "files/output-onlinegiftools.gif",
//    "loadingCaptionColor": "#000000",
    "loadingCaptionColor": "#e3e3e3",
//    "loadingBackground": "#c7c7c7",
    "loadingBackground": "#323232",
    "logoHeight": 42,
    "logoTop": 0,
    "logoPadding": 0,
    "HomeButtonVisible": "Hide",
    "ShareButtonVisible": "Show",
    "largenailsButtonVisible": "Show",
    "largenailAlpha": 70,
    "ZoomButtonVisible": "Show",
    "FullscreenButtonVisible": "Show",
    "TableOfContentButtonVisible": "Hide",
    "SearchButtonVisible": "Hide",
    "leastSearchChar": 2,
    "PrintButtonVisible": "Show",
    "printWatermarkFile": "",
    "BookMarkButtonVisible": "Show",
    "BackgroundSoundButtonVisible": "Show",
    "BackgroundSoundURL": "https://kingsiddhu.github.io/XI-Phy-Sample-Record-Book/files/lukrembo-bread_LASsYFKc.mp3",
    //"BackgroundSoundURL": "",
    "BackgroundSoundLoop": -1,
    "HelpButtonVisible": "True",
    "helpContentFileURL": "",
    "helpWidth": 400,
    "helpHeight": 450,
    "showHelpContentAtFirst": "No",
    "aboutButtonVisible": "Hide",
    "aboutContactInfoTxt": "",
    "AutoPlayButtonVisible": "Show",
    "autoPlayAutoStart": "No",
    "SlideshowAutoPlay": false,
    "autoPlayDuration": 3,
    "SlideshowPlayInterval": 5,
    "autoPlayLoopCount": "1",
    "minZoomWidth": 403,
    "minZoomHeight": 518,
    "mouseWheelFlip": "Yes",
    "DownloadButtonVisible": "Hide",
    "DownloadURL": "",
    "UserInforSetting": "",
    "bgBeginColor": "#323232",
    "bgEndColor": "#323232",
    "bgMRotation": 90,
    "backGroundImgURL": "",
    "LeftShadowWidth": 100,
    "LeftShadowAlpha": 1,
    "RightShadowWidth": 40,
    "RightShadowAlpha": 1,
    "pageBackgroundColor": "#FFFFFF",
    "flipshortcutbutton": "Show",
    "OriginPageIndex": 1,
    "RightToLeft": "No",
    "flippingTime": 0.6,
    "retainBookCenter": "Yes",
    "FlipStyle": "Flip",
    "totalPagesCaption": "",
    "pageNumberCaption": "",
    "topMargin": 10,
    "bottomMargin": 10,
    "leftMargin": 10,
    "rightMargin": 10,
    "LinkDownColor": "#0000FF",
    "LinkAlpha": 0.4,
    "OpenWindow": "Blank",
    "googleAnalyticsID": "",
    "UIBaseURL": "\/\/static.fliphtml5.com\/book\/template\/Metro\/",
    "language": "English",
    "AboutAddress": "",
    "AboutAuthor": "",
    "AboutEmail": "",
    "AboutMobile": "",
    "AboutWebsite": "",
    "AboutDescription": "",
    "totalPageCount": 88,
    "largePageWidth": 603,
    "largePageHeight": 783,
    "normalPath": "files\/large\/",
    "largePath": "files\/large\/",
    "largePath": "files\/large\/",
    "VideoButtonVisible": "Hide",
    "SlideshowButtonVisible": "Hide",
    "addPaperCoil": "Yes",
    "AnnotationButtonVisible": "Hide",
    "CompanyLogoFile": "",
    "bleedAreaLeft": "0%",
    "bleedAreaRight": "0%",
    "bleedAreaTop": "0%",
    "bleedAreaBottom": "0%",
    "HardPageEnable": "No",
    "HardInnerPageEnable": "No",
    "borderColor": "#562e0b",
    "BindingType": "side",
    "hardCoverBorderWidth": "8",
    "outerCoverBorder": "Yes",
    "cornerRound": "8",
    "coverTexture": "none",
    "iconFontColor": "#eeeeee",
    "formBackgroundColor": "#181818",
    "formFontColor": "#eeeeee",
    "backgroundOpacity": "100",
    "autoDoublePage": "Auto",
    "searchKeywordFontColor": "#FFB000",
    "backgroundPosition": "Stretch",
    "CurlingPageCorner": "Yes",
    "updatePageURL": "True",
    "isTheBookOpen": "No",
    "FlipDirection": "0",
    "InstructionsButtonVisible": "Hide",
    "showInstructionOnStart": "No",
    "showThicknessOnMobile": "No",
    "highDefinitionConversion": "No",
    "pageNumColor": "#111111",
    "backgroundScene": "None",
    "ShowTopLeftShadow": "Yes",
    "maxWidthToSmallMode": 400,
    "maxHeightToSmallMode": 300,
    "hideMiniFullscreen": "No",
    "isStopMouseMenu": "No",
    "haveAdSense": "No",
    "adSenseWidth": 200,
    "adSenseHeight": 200,
    "adSenseLeft": 50,
    "adSenseTop": 50,
    "adSenseClientId": "",
    "SelectTextButtonVisible": "Hide",
    "leftRightPnlShowOption": "none",
    "ToolBarAlpha": "1",
    "enablePageBack": "Hide",
    "TitleBarColor": "#444444",
    "CreatedTime": 1646765789,
    "loadingCaption": "",
    "phoneFlipShortcutButton": "Hide",
    "searchTextJS": "files\/search\/book_config.js",
    "searchPositionJS": "files\/search\/text_position[%d].js"
};var fliphtml5_pages=[
    {"l":"files/large/Start.jpg","t":"files/thumb/1.jpg"},
    {"l":"files/large/2.jpg","t":"files/thumb/2.jpg"},
    {"l":"files/large/3.jpg","t":"files/thumb/3.jpg"},
    {"l":"files/large/4.jpg","t":"files/thumb/4.jpg"},
    {"l":"files/large/5.jpg","t":"files/thumb/5.jpg"},
    {"l":"files/large/6.jpg","t":"files/thumb/6.jpg"},
    {"l":"files/large/7.jpg","t":"files/thumb/7.jpg"},
    {"l":"files/large/8.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/9.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/9.1.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/9.2.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/10.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/11.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/12.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/13.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/14.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/15.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/16.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/17.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/18.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/19.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/20.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/21.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/22.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/23.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/24.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/25.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/26.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/27.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/28.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/29.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/30.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/31.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/32.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/33.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/34.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/35.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/36.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/37.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/38.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/39.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/40.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/43.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/44.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/45.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/46.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/47.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/48.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/49.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/50.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/51.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/52.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/53.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/54.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/55.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/56.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/57.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/58.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/59.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/60.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/61.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/62.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/63.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/64.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/65.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/66.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/67.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/68.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/69.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/70.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/71.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/72.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/73.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/74.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/75.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/76.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/77.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/78.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/79.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/80.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/81.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/82.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/83.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/84.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/85.jpg","t":"files/thumb/8.jpg"},
    {"l":"files/large/end.jpg","t":"files/thumb/8.jpg"},];
var language = [{"language":"English","btnFirstPage":"First","btnNextPage":"Next","btnLastPage":"Last","btnPrePage":"Previous","btnGoToHome":"Home","btnDownload":"Download","btnSoundOn":"Sound On","btnSoundOff":"Sound Off","btnPrint":"Print","btnlarge":"largenails","btnBookMark":"Bookmark","frmBookMark":"Bookmark","btnZoomIn":"Zoom In","btnZoomOut":"Zoom Out","btnAutoFlip":"Auto Flip","btnStopAutoFlip":"Stop Auto Flip","btnSocialShare":"Share","btnHelp":"Help","btnAbout":"About","btnSearch":"Search","btnFullscreen":"Fullscreen","btnExitFullscreen":"Exit Fullscreen","btnMore":"More","frmPrintCaption":"Print","frmPrintall":"Print All Pages","frmPrintcurrent":"Print Current Page","frmPrintRange":"Print Range","frmPrintexample":"Example: 2,3,5-10","frmPrintbtn":"Print","frmShareCaption":"Share","frmShareLabel":"Share","frmShareInfo":"You can easily share this publication to social networks.Just click the appropriate button below","frminsertLabel":"Insert to Site","frminsertInfo":"Use the code below to embed this publication to your website.","frmaboutcaption":"Contact","frmaboutcontactinformation":"Contact Information","frmaboutADDRESS":"Address","frmaboutEMAIL":"Email","frmaboutWEBSITE":"Website","frmaboutMOBILE":"Mobile","frmaboutAUTHOR":"Author","frmaboutDESCRIPTION":"Description","frmSearch":"Search","frmToc":"Table Of Contents","btnTableOfContent":"Table Of Contents","btnNote":"Annotation","lblLast":"This is the last page.","lblFirst":"This is the first page.","lblFullscreen":"Click to view in fullscreen","lblName":"Name","lblPassword":"Password","lblLogin":"Login","lblCancel":"Cancel","lblNoName":"User name can not be empty.","lblNoPassword":"Password can not be empty.","lblNoCorrectLogin":"Please enter the correct user name and password.","btnVideo":"Video Gallery","btnSlideShow":"Slideshow","pnlSearchInputInvalid":"The search text is too short.","btnDragToMove":"Move by mouse drag","btnPositionToMove":"Move by mouse position","lblHelp1":"Drag the page corner to view","lblHelp2":"Double click to zoom in, out","lblCopy":"Copy","lblAddToPage":"Add To Page","lblPage":"Page","lblTitle":"Title","lblEdit":"Edit","lblDelete":"Delete","lblRemoveAll":"Remove All","tltCursor":"Cursor","tltAddHighlight":"Add highlight","tltAddTexts":"Add texts","tltAddShapes":"Add shapes","tltAddNotes":"Add notes","tltAddImageFile":"Add image file","tltAddSignature":"Add signature","tltAddLine":"Add line","tltAddArrow":"Add arrow","tltAddRect":"Add rect","tltAddEllipse":"Add ellipse","lblDoubleClickToZoomIn":"Double click to zoom in.","lblPages":"Pages","infCopyToClipboard":"Your browser dose not support clipboard, please do it yourself.","lblDescription":"Title","frmLinkLabel":"Link","infNotSupportHtml5":"HTML5 is not supported by your current web browser, please read the book with latest verson web browser. Here we recommend you to read it with Chrome.","frmHowToUse":"How To Use","lblHelpPage1":"Move your finger to flip the book page.","lblHelpPage2":"Zoom in by using gesture or double click on the page.","lblHelpPage3":"Click to view the table of content, bookmarks and share your books via social networks.","lblHelpPage4":"Add bookmarks, use search function and auto flip the book.","lblHelpPage5":"Open the largenails to overview all book pages.","frmQrcodeCaption":"Scan the bottom two-dimensional code to view with mobile phone.","btnPageBack":"Backward","btnPageForward":"Forward","btnLanguage":"Change Language","msgConfigMissing":"Configuration file is missing, unable to open the book."}];;
var pageEditor = {"setting":{}, "pageAnnos":[[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]};
var ols = [];
var slideshow = [];
var videoList = [];
var bmtConfig = {"tabs":[],"onSideEdge":true};
var staticAd = {};
var flipByAudio = {};
var bookPlugin = null;
var phoneNumber = [];bookConfig.language="English";
